apiVersion: v1
kind: Service
metadata:
  name: lightweight-charts-web
  labels:
    app: lightweight-charts-web
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: lightweight-charts-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
